### ISSUE TITLE
Errors when trying to read/modify config file

### ISSUE THREAD

**Issue by sponegg** [Alchemy4Tridion/Alchemy4Tridion#11] opened 2015-06-16 13:35 UTC
I get an error about a lack of permissions to read/modify a config file, every time I try to install or uninstall a plugin.

**Comment by alex-klock** [comment] 2015-06-22 00:55
Can we verify this is duplicate of issue #1 ?

**Comment by alex-klock** [comment] 2015-06-23 17:04
Making assumption its duplicate, 0.4.2 fixes should resolve this.

**Closed as completed** 2015-06-23 17:04 UTC
Labels: duplicate
